HAI
    WAZZUP
    BUHBYE
    BOTH SAEM 2 AN 1
    BOTH SAEM 2 AN 2
    DIFFRINT 1 AN 1
    DIFFRINT 1 AN 2
    BOTH SAEM 2 AN BIGGR OF SUM OF 2 AN 2 AN 1
    DIFFRINT 3 AN SMALLR OF SUM OF 2 AN 3 AN 4
KTHXBYE